# main ƒuƒ‰ƒ“ƒ`‚É‰½‚ç‚©‚Ì commit ‚ª’Ç‰Á‚³‚ê‚½‚ç‘–‚ç‚¹‚é
on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: twihigh-dev-func-appusers
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/PheasantTails.TwiHigh.Functions.TwiHighUsers'
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_APPUSERS_PUBLISH }}

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples