#---------------------------------------------------------------------------------------
#   deploy-dev.yml
#       refer to https://github.com/Azure/actions-workflow-samples
#---------------------------------------------------------------------------------------
name: Deploy Follows function
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/deploy-follows-function.yml'
      - 'src/PheasantTails.TwiHigh.Data.Model/**'
      - 'src/PheasantTails.TwiHigh.Data.Store/**'
      - 'src/PheasantTails.TwiHigh.Functions.Core/**'
      - 'src/PheasantTails.TwiHigh.Functions.Extensions/**'
      - 'src/PheasantTails.TwiHigh.Functions.Follows/**'

jobs:
  dev-build-and-deploy-follows:
    name: PRO:Build and deploy Follows
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      function-app-name: twihigh-pro-func-follows
      function-project-path: ./src/PheasantTails.TwiHigh.Functions.Follows
      deploy-environment-name: pro-func-follows
    secrets:
      publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PRO_FOLLOWS }}

  pro-build-and-deploy-follows:
    name: DEV:Build and deploy Follows
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      function-app-name: twihigh-dev-func-follows
      function-project-path: ./src/PheasantTails.TwiHigh.Functions.Follows
      deploy-environment-name: dev-func-follows
    secrets:
      publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_DEV_FOLLOWS }}