#---------------------------------------------------------------------------------------
#   deploy-dev.yml
#       refer to https://github.com/Azure/actions-workflow-samples
#---------------------------------------------------------------------------------------
name: Deploy Timelines function
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/deploy-timelines-function.yml'
      - 'src/PheasantTails.TwiHigh.Data.Model/**'
      - 'src/PheasantTails.TwiHigh.Functions.Core/**'
      - 'src/PheasantTails.TwiHigh.Functions.Timelines/**'
      - 'src/PheasantTails.TwiHigh.Interface/**'

jobs:
  pro-build-and-deploy-timelines:
    name: PRO:Build and deploy Timelines
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      function-app-name: twihigh-pro-func-timelines
      function-project-path: ./src/PheasantTails.TwiHigh.Functions.Timelines
      deploy-environment-name: pro-func-timelines
    secrets:
      publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PRO_TIMELINES }}
      
  dev-build-and-deploy-timelines:
    name: DEV:Build and deploy Timelines
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      function-app-name: twihigh-dev-func-timelines
      function-project-path: ./src/PheasantTails.TwiHigh.Functions.Timelines
      deploy-environment-name: dev-func-timelines
    secrets:
      publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_DEV_TIMELINES }}