#---------------------------------------------------------------------------------------
#   deploy-dev.yml
#       refer to https://github.com/Azure/actions-workflow-samples
#---------------------------------------------------------------------------------------
name: Build and Deploy Client
on:
  push:
    branches:
      - main
    paths:
      - 'src/PheasantTails.TwiHigh.Client/**'
      - 'src/PheasantTails.TwiHigh.Data.Model/**'
      - 'src/PheasantTails.TwiHigh.Data.Store/**'

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    name: Build and Deploy Client
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy Client
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # ref: https://aka.ms/swaworkflowconfig
          app_location: "src/PheasantTails.TwiHigh.Client" # App source code path
          output_location: "wwwroot" # Built app content directory - optional
          skip_api_build: true
          production_branch: "main"