#---------------------------------------------------------------------------------------
#   deploy-dev.yml
#       refer to https://github.com/Azure/actions-workflow-samples
#---------------------------------------------------------------------------------------
# main ƒuƒ‰ƒ“ƒ`‚É‰½‚ç‚©‚Ì commit ‚ª’Ç‰Á‚³‚ê‚½‚ç‘–‚ç‚¹‚é
on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: twihigh-dev-func-appusers
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/PheasantTails.TwiHigh.Functions.TwiHighUsers'
  DOTNET_VERSION: '6.0.x'

jobs:
  # Follows
  build-and-deploy-follows:
    name: Build and deploy Follows
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      function-app-name: twihigh-dev-func-follows
      function-project-path: ./src/PheasantTails.TwiHigh.Functions.Follows
    secrets:
      publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_DEV_FOLLOWS }}

  # Timelines
  build-and-deploy-timelines:
    name: Build and deploy Timelines
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      function-app-name: twihigh-dev-func-timelines
      function-project-path: ./src/PheasantTails.TwiHigh.Functions.Timelines
    secrets:
      publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_DEV_TIMELINES }}

  # Tweets
  build-and-deploy-tweets:
    name: Build and deploy Tweets
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      function-app-name: twihigh-dev-func-tweets
      function-project-path: ./src/PheasantTails.TwiHigh.Functions.Tweets
    secrets:
      publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_DEV_TWEETS }}

  # TwiHighUsers
  build-and-deploy-twihighusers:
    name: Build and deploy TwiHighUsers
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      function-app-name: twihigh-dev-func-twihighusers
      function-project-path: ./src/PheasantTails.TwiHigh.Functions.TwiHighUsers
    secrets:
      publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_DEV_TWIHIGHUSERS }}

  # Client
  build-and-deploy-client:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Client
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy Client
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # ref: https://aka.ms/swaworkflowconfig
          app_location: "src/PheasantTails.TwiHigh.Client" # App source code path
          output_location: "wwwroot" # Built app content directory - optional
          skip_api_build: true
          production_branch: "main"