#---------------------------------------------------------------------------------------
#   deploy-dev.yml
#       refer to https://github.com/Azure/actions-workflow-samples
#---------------------------------------------------------------------------------------
name: Deploy TwiHighUsers function
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/deploy-twihighusers-function.yml'
      - 'src/PheasantTails.TwiHigh.Data.Model/**'
      - 'src/PheasantTails.TwiHigh.Data.Store/**'
      - 'src/PheasantTails.TwiHigh.Functions.Core/**'
      - 'src/PheasantTails.TwiHigh.Functions.Extensions/**'
      - 'src/PheasantTails.TwiHigh.Functions.TwiHighUsers/**'

jobs:
  pro-build-and-deploy-twihighusers:
    name: PRO:Build and deploy TwiHighUsers
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      function-app-name: twihigh-pro-func-twihighusers
      function-project-path: ./src/PheasantTails.TwiHigh.Functions.TwiHighUsers
      deploy-environment-name: pro-func-twihighusers
    secrets:
      publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PRO_TWIHIGHUSERS }}
      
  dev-build-and-deploy-twihighusers:
    name: DEV:Build and deploy TwiHighUsers
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      function-app-name: twihigh-dev-func-twihighusers
      function-project-path: ./src/PheasantTails.TwiHigh.Functions.TwiHighUsers
      deploy-environment-name: dev-func-twihighusers
    secrets:
      publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_DEV_TWIHIGHUSERS }}